DATA_PATH = "./data"

BALLS_PATH = DATA_PATH + "/balls"
BALLS_TRAIN_PATH = BALLS_PATH + "/train"
BALLS_TEST_PATH = BALLS_PATH + "/test"
BALLS_VALID_PATH = BALLS_PATH + "/valid"

BASKETBALL_TRAIN_PATH = BALLS_TRAIN_PATH + "/basketball"
BASKETBALL_TEST_PATH = BALLS_TEST_PATH + "/basketball"
BASKETBALL_VALID_PATH = BALLS_VALID_PATH + "/basketball"

COLORS_PATH = DATA_PATH + "/colors"
ORANGE_PATH = COLORS_PATH + "/orange"

MODEL_PATH = DATA_PATH + "/model.pt"
